using AutomatedContentGuard.Data;
using AutomatedContentGuard.Interfaces;
using AutomatedContentGuard.Repositories;
using AutomatedContentGuard.Services;
using Microsoft.EntityFrameworkCore;

// Fix for Npgsql / PostgreSQL DateTime timestamp mapping issues
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// 1. Add CORS Policy
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyHeader()
              .AllowAnyMethod();
    });
});

// 2. Add Controllers and Swagger
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// 3. Register DbContext with Neon PostgreSQL
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

// 4. Register Repositories
builder.Services.AddScoped<IContentRepository, ContentSubmissionRepo>();
builder.Services.AddScoped<IForbiddenWordRepository, ForbiddenWordRepo>();

// 5. Register Services
builder.Services.AddScoped<IContentSubmissionService, ContentSubmissionService>();
builder.Services.AddScoped<IForbiddenWordService, ForbiddenWordService>();

// Register HttpClient for Gemini/HuggingFace Moderation
builder.Services.AddHttpClient<GeminiModerationService>();

var app = builder.Build();

// CRITICAL FIX: Place CORS at the very top of the HTTP pipeline
app.UseCors("AllowAll");

// DIRECT AUTO-CREATE SCHEMAS ON STARTUP
using (var scope = app.Services.CreateScope())
{
    try
    {
        var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        // Explicit raw SQL script to guarantee ContentSubmissions table & all required fields exist
        string createTablesSql = @"
            CREATE TABLE IF NOT EXISTS ""ContentSubmissions"" (
                ""Id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""TextContent"" TEXT NOT NULL,
                ""ToxicityScore"" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
                ""IsFlagged"" BOOLEAN NOT NULL DEFAULT FALSE,
                ""Status"" TEXT NOT NULL DEFAULT 'Approved',
                ""CreatedAt"" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
                ""SubmittedAt"" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
            );

            CREATE TABLE IF NOT EXISTS ""ForbiddenWords"" (
                ""Id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Word"" TEXT NOT NULL,
                ""CreatedAt"" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
            );
        ";

        dbContext.Database.ExecuteSqlRaw(createTablesSql);

        Console.WriteLine("[Database System]: Neon PostgreSQL tables directly verified and created.");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[DB Initialization Warning]: {ex.Message}");
    }
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseAuthorization();
app.MapControllers();

app.Run();
